name: "commit-swr"

on:
  push:
    branches: 
    - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Comprobando la version de docker
    - name: check docker version
      run: docker -v
      
    # docker login, login en SWR
    - name: Log in to HuaweiCloud SWR
      uses: huaweicloud/swr-login@v1
      with:
        region: ap-southeast-3
        access-key-id: ${{ secrets.ACCESSKEY }}
        access-key-secret: ${{ secrets.SECRETACCESSKEY }}

    # Configurar el entorno de docker
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    # build and push docker image
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        #context: ./
        #file: ./Dockerfile

        #tags: swr.na-mexico-1.myhuaweicloud.com/cicd-test/react-app:v2
        #sudo docker push swr.ap-southeast-3.myhuaweicloud.com/{Organization name}/{Image name}:{Tag}

        push: true
        tags: swr.ap-southeast-3.myhuaweicloud.com/cloudbuildtest/webtest2:v1



