name: HUAWEI SWR IMAGE UPLOAD WITH REPO AND POLICY
author: Fredy Olarte 
branding:
  icon: upload-cloud
  color: orange
description: Create Docker images and push into a SWR repository. It can create it and attach a policy to store a max amount
inputs:
  access_key_id: ${{ secrets.ACCESSKEY }}
    description: "The HUAWEI access key id"
    required: true
  secret_access_key: ${{ secrets.SECRETACCESSKEY }}
    description: The HUAWEI secret access key
    required: true
  swr_registry: swr.ap-southeast-3.myhuaweicloud.com/cloudbuildtest/codeartscicd
    description: The HUAWEI SWR Registry
    required: true
  repo: codeartscicd
    description: Name of your SWR repository
    required: true
  region: ap-southeast-3
    description: The HUAWEI region
    default: "ap-southeast-3"
    required: true
  tags:  
    description: Comma-separated string of SWR image tags
    default: "latest"
    required: false
    
  #build and push docker image
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        #context: ./
        #file: ./Dockerfile

        push: true
        tags:  
